<?php
$helper = $this->getHelper();
if($helper->getDynamicRemarketingEnabled()): ?>
	<script type="text/javascript">
		var google_tag_params = <?php echo $this->getJsConfigParams(); ?>;
	</script>
<?php endif;?>
<script type="text/javascript">
	/* <![CDATA[ */
	var google_conversion_id = <?php echo $helper->getGoogleConversionId(); ?>;
	var google_custom_params = window.google_tag_params;
	var google_remarketing_only = true;
	/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js"></script>

<noscript>
	<div style="display:inline;">
		<img height="1" width="1" style="border-style:none;" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/<?php echo $helper->getGoogleConversionId();?>/?value=0&amp;guid=ON&amp;script=0"/>
	</div>
</noscript>