<?php
/**
* Copyright 2016 aheadWorks. All rights reserved.
* See LICENSE.txt for license details.
*/

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

/* @var $block \Aheadworks\Autorelated\Block\Related */
?>
<?php if ($arpBlocks = $block->getBlocks()) : ?>
    <?php foreach ($arpBlocks as $arpBlock) : ?>
        <div
                data-aw-arp-block-rule-id="<?php /* @noEscape */ echo $block->getRuleIdForBlock($arpBlock) ?>"
                data-mage-init='<?php /* @noEscape */ echo $block->getDataMageInitForBlock($arpBlock) ?>'
                class="aw-arp-container <?php /* @noEscape */ echo $block->getAdditionalCssClassesForBlock($arpBlock) ?>"
                style="visibility: hidden"
        >
            <h3 class="aw-arp-container__title"><?php echo $block->escapeHtml($arpBlock->getRule()->getTitle()) ?></h3>
            <div data-aw-arp-block="items" class="aw-arp-container__items">
                <?php foreach ($arpBlock->getProductIds() as $productId) : ?>
                    <?php if (is_null($productModel = $block->getProductById($productId))) : ?>
                        <?php continue; ?>
                    <?php endif ?>
                    <div data-aw-arp-block="item" class="aw-arp-container__item">
                        <div class="product-item">
                            <div class="product-item-info">
                                <?php $productUrl = $block->getProductUrl($productModel) ?>
                                <a data-mage-init='{"awArpRedirect": {}}'
                                   data-aw-arp-rule-id="<?php /* @noEscape */ echo $block->getRuleIdForBlock($arpBlock) ?>"
                                   data-aw-arp-encode-url="<?php /* @noEscape */ echo $block->encodeUrl($productUrl) ?>"
                                   href="<?php /* @noEscape */ echo $productUrl ?>"
                                   class="product-item-photo">
                                            <span class="product-image-container">
                                                <span class="product-image-wrapper">
                                                    <img class="product-image-photo"
                                                         src="<?php /* @noEscape */ echo $block->getImage($productModel, 'product_base_image')->getImageUrl(); ?>"
                                                         width="240" height="300" alt="<?php echo $block->escapeHtml($productModel->getName()) ?>">
                                                </span>
                                            </span>
                                </a>

                                <div class="product-item-details">
                                    <strong class="product-item-name">
                                        <a data-mage-init='{"awArpRedirect": {}}'
                                           data-aw-arp-rule-id="<?php /* @noEscape */ echo $block->getRuleIdForBlock($arpBlock) ?>"
                                           data-aw-arp-encode-url="<?php /* @noEscape */ echo $block->encodeUrl($productUrl) ?>"
                                           title="<?php echo $block->escapeHtml($productModel->getName()) ?>"
                                           href="<?php /* @noEscape */ echo $productUrl ?>"
                                           class="product-item-link"><?php echo $block->escapeHtml($productModel->getName()) ?></a>
                                    </strong>

                                    <div class="price-box">
                                        <?php /* @noEscape */ echo $block->getProductPrice($productModel) ?>
                                    </div>
                                    <?php if ($arpBlock->getRule()->getIsDisplayAddToCart()) : ?>
                                        <div class="actions-primary">
                                            <?php if ($productModel->isSaleable()): ?>
                                                <?php $addToCartUrl = $block->getAddToCartUrl($productModel, ['awarp_rule' => $arpBlock->getRule()->getId()]); ?>
                                                <form data-role="tocart-form"
                                                      action="<?php /* @noEscape */ echo $addToCartUrl; ?>"
                                                      method="post" data-mage-init='{"catalogAddToCart": {}}'>
                                                    <?php /* @noEscape */ echo $block->getFormKeyHtml() ?>
                                                    <input type="hidden" name="product" value="<?php /* @noEscape */ echo $productModel->getEntityId(); ?>">
                                                    <input type="hidden" name="<?php /* @noEscape */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @noEscape */ echo $block->encodeUrl($addToCartUrl); ?>">
                                                    <button type="submit"
                                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                            class="action tocart primary">
                                                        <span><?php echo $block->escapeHtml(__('Add to Cart')) ?></span>
                                                    </button>
                                                </form>
                                            <?php else: ?>
                                                <?php if ($productModel->getIsSalable()): ?>
                                                    <div class="stock available">
                                                        <span><?php echo $block->escapeHtml(__('In stock')) ?></span>
                                                    </div>
                                                <?php else: ?>
                                                    <div class="stock unavailable">
                                                        <span><?php echo $block->escapeHtml(__('Out of stock')) ?></span>
                                                    </div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif ?>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endforeach ?>
            </div>
        </div>
    <?php endforeach ?>
<?php endif; ?>
