<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_Checkout
 */
?>
<?php /** @var \Amasty\Checkout\Block\Sales\Order\Info\Delivery $block */?>
<?php if ($fields = $block->getDeliveryDateFields()): ?>
    <div class="delivery">
    <?php foreach ($fields as $field): ?>
        <div class="delivery-field">
            <?= __($field['label']); ?>: <?= $field['value']; ?>
        </div>
    <?php endforeach; ?>
    </div>
<?php endif ?>
