#! /bin/bash
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/layout/datafeedmanager_variables_index.xml
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/layout/datafeedmanager_functions_index.xml
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/layout/datafeedmanager_variables_edit.xml
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/layout/datafeedmanager_functions_edit.xml
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/layout/datafeedmanager_feeds_preview.xml
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/layout/datafeedmanager_feeds_index.xml
rm ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/Functions/AbstractFunctions.php
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/layout/datafeedmanager_feeds_edit.xml
rm ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/Variables/AbstractVariables.php
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/templates/variables_functions.phtml
rm ./app/code/Wyomind/Core/view/frontend/layout/licensemanager_activation_webservice.xml
rm ./app/code/Wyomind/DataFeedManager/Model/ResourceModel/Product/Option/Collection.php
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/templates/edit/configuration.phtml
rm ./app/code/Wyomind/DataFeedManager/Block/Adminhtml/Feeds/Edit/Tab/Configuration.php
rm ./app/code/Wyomind/Core/Block/Adminhtml/System/Config/Form/Field/ActivationFlag.php
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/templates/edit/categories.phtml
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/javascript/javascript.js
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/web/css/variables_functions.css
rm ./app/code/Wyomind/DataFeedManager/Block/Adminhtml/Feeds/Edit/Tab/Categories.php
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/templates/edit/translate.phtml
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/templates/edit/blackbox.phtml
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/web/js/feeds/configuration.js
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/templates/edit/utils.js.phtml
rm ./app/code/Wyomind/DataFeedManager/Model/ResourceModel/Variables/Collection.php
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/htmlmixed/htmlmixed.js
rm ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/Feeds/Librarysample.php
rm ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/Variables/NewAction.php
rm ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/Functions/NewAction.php
rm ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/Feeds/AbstractFeeds.php
rm ./app/code/Wyomind/DataFeedManager/Model/ResourceModel/Functions/Collection.php
rm ./app/code/Wyomind/Core/view/adminhtml/layout/adminhtml_system_config_edit.xml
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/templates/edit/filters.phtml
rm ./app/code/Wyomind/DataFeedManager/Model/ResourceModel/Product/Collection.php
rm ./app/code/Wyomind/DataFeedManager/data/Google/Taxonomies/[default] en_US.txt
rm ./app/code/Wyomind/DataFeedManager/Block/Adminhtml/Feeds/Edit/Tab/Filters.php
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/web/js/feeds/categories.js
rm ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/Variables/Delete.php
rm ./app/code/Wyomind/DataFeedManager/Model/ResourceModel/Review/Collection.php
rm ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/Functions/Delete.php
rm ./app/code/Wyomind/DataFeedManager/data/Google/Requirements/Requirements.php
rm ./app/code/Wyomind/DataFeedManager/Block/Adminhtml/Feeds/Renderer/Action.php
rm ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/Feeds/Categories.php
rm ./app/code/Wyomind/DataFeedManager/Block/Adminhtml/Feeds/Renderer/Status.php
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/web/images/ajax-loader.gif
rm ./app/code/Wyomind/DataFeedManager/Model/ResourceModel/Feeds/Collection.php
rm ./app/code/Wyomind/DataFeedManager/Model/ResourceModel/Store/Collection.php
rm ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/Variables/Index.php
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/web/css/configuration.css
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/templates/edit/cron.phtml
rm ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/Feeds/NewAction.php
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/web/images/library-tv.png
rm ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/Functions/Index.php
rm ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/Variables/Edit.php
rm ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/AbstractAction.php
rm ./app/code/Wyomind/DataFeedManager/Block/Adminhtml/Feeds/Renderer/Link.php
rm ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/Variables/Save.php
rm ./app/code/Wyomind/DataFeedManager/Block/Adminhtml/Functions/Edit/Form.php
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/templates/edit/ftp.phtml
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/web/js/feeds/blackbox.js
rm ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/Functions/Save.php
rm ./app/code/Wyomind/DataFeedManager/Block/Adminhtml/Variables/Edit/Form.php
rm ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/Functions/Edit.php
rm ./app/code/Wyomind/DataFeedManager/Block/Adminhtml/Feeds/Renderer/Type.php
rm ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/Feeds/Generate.php
rm ./app/code/Wyomind/DataFeedManager/Block/Adminhtml/Feeds/Edit/Tab/Cron.php
rm ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/Feeds/Updater.php
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/matchbrackets.js
rm ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/Feeds/Library.php
rm ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/Feeds/Preview.php
rmdir  ./app/code/Wyomind/DataFeedManager/Model/ResourceModel/Product/Option
rm ./app/code/Wyomind/DataFeedManager/Block/Adminhtml/Feeds/Edit/Tab/Ftp.php
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/templates/preview.phtml
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/web/js/feeds/filters.js
rm ./app/code/Wyomind/DataFeedManager/Helper/AttributesStockInTheChannel.php
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/templates/import.phtml
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/web/css/categories.css
rm ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/Feeds/Delete.php
rm ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/Feeds/Sample.php
rm ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/Feeds/Import.php
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/email/cron_report.html
rm ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/Feeds/Export.php
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/web/images/resize.png
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/javascript
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/codemirror.css
rm ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/Feeds/Index.php
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/web/images/loader.gif
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/templates/empty.phtml
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/templates/index.phtml
rm ./app/code/Wyomind/DataFeedManager/Model/ResourceModel/RelationShip.php
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/clike/clike.js
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/web/js/feeds/index.js
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/active-line.js
rm ./app/code/Wyomind/DataFeedManager/Block/Adminhtml/Feeds/Edit/Form.php
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/htmlmixed
rm ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/Feeds/Edit.php
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/web/css/blackbox.css
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/formatting.js
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/web/js/feeds/cron.js
rm ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/Feeds/Save.php
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/codemirror.js
rm ./app/code/Wyomind/DataFeedManager/Block/Adminhtml/Feeds/Edit/Tabs.php
rmdir  ./app/code/Wyomind/DataFeedManager/Block/Adminhtml/Feeds/Edit/Tab
rmdir  ./app/code/Wyomind/DataFeedManager/Block/Adminhtml/Functions/Edit
rm ./app/code/Wyomind/DataFeedManager/Block/Adminhtml/Functions/Grid.php
rmdir  ./app/code/Wyomind/DataFeedManager/Block/Adminhtml/Variables/Edit
rm ./app/code/Wyomind/DataFeedManager/Block/Adminhtml/Variables/Edit.php
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/web/css/filters.css
rmdir  ./app/code/Wyomind/DataFeedManager/Block/Adminhtml/Feeds/Renderer
rm ./app/code/Wyomind/DataFeedManager/Helper/AttributesCustomOptions.php
rm ./app/code/Wyomind/DataFeedManager/Block/Adminhtml/Variables/Grid.php
rm ./app/code/Wyomind/DataFeedManager/Block/Adminhtml/Functions/Edit.php
rmdir  ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/Functions
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/requirejs-config.js
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/web/js/feeds/ftp.js
rm ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/Feeds/Ftp.php
rmdir  ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/Variables
rm ./app/code/Wyomind/DataFeedManager/Block/Adminhtml/Feeds/Preview.php
rmdir  ./app/code/Wyomind/DataFeedManager/view/adminhtml/templates/edit
rm ./app/code/Wyomind/DataFeedManager/Model/ResourceModel/Variables.php
rmdir  ./app/code/Wyomind/Core/Block/Adminhtml/System/Config/Form/Field
rm ./app/code/Wyomind/DataFeedManager/Model/ResourceModel/TierPrice.php
rmdir  ./app/code/Wyomind/DataFeedManager/Model/ResourceModel/Functions
rmdir  ./app/code/Wyomind/DataFeedManager/Model/ResourceModel/Variables
rm ./app/code/Wyomind/DataFeedManager/Model/ResourceModel/Functions.php
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/php/php.js
rm ./app/code/Wyomind/DataFeedManager/data/Google/Taxonomies/nl_NL.txt
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/xml/xml.js
rm ./app/code/Wyomind/DataFeedManager/data/Google/Taxonomies/it_IT.txt
rm ./app/code/Wyomind/DataFeedManager/Model/ResourceModel/TaxClass.php
rm ./app/code/Wyomind/DataFeedManager/data/Google/Taxonomies/fr_FR.txt
rm ./app/code/Wyomind/DataFeedManager/data/Google/Taxonomies/en_GB.txt
rm ./app/code/Wyomind/DataFeedManager/data/Google/Taxonomies/es_ES.txt
rm ./app/code/Wyomind/DataFeedManager/data/Google/Taxonomies/en_AU.txt
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/css/css.js
rm ./app/code/Wyomind/DataFeedManager/data/Google/Taxonomies/de_DE.txt
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/web/images/d.png
rm ./app/code/Wyomind/DataFeedManager/view/adminhtml/web/css/cron.css
rmdir  ./app/code/Wyomind/DataFeedManager/view/adminhtml/web/js/feeds
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/clike
rm ./app/code/Wyomind/DataFeedManager/Helper/AttributesCategories.php
rmdir  ./app/code/Wyomind/DataFeedManager/Model/ResourceModel/Product
rm ./app/code/Wyomind/DataFeedManager/Model/ResourceModel/Images.php
rmdir  ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml/Feeds
rmdir  ./app/code/Wyomind/DataFeedManager/Model/ResourceModel/Review
rm ./app/code/Wyomind/DataFeedManager/Helper/AttributesInventory.php
rm ./app/code/Wyomind/DataFeedManager/Block/Adminhtml/Feeds/Grid.php
rm ./app/code/Wyomind/DataFeedManager/Block/Adminhtml/Feeds/Edit.php
rmdir  ./app/code/Wyomind/DataFeedManager/Block/Adminhtml/Feeds/Edit
rm ./app/code/Wyomind/DataFeedManager/Controller/Feeds/Generate.php
rmdir  ./app/code/Wyomind/DataFeedManager/Block/Adminhtml/Functions
rm ./app/code/Wyomind/DataFeedManager/Block/Adminhtml/Functions.php
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/php
rm ./app/code/Wyomind/DataFeedManager/Model/ResourceModel/Feeds.php
rm ./app/code/Wyomind/Core/view/frontend/templates/webservice.phtml
rmdir  ./app/code/Wyomind/DataFeedManager/Model/ResourceModel/Feeds
rm ./app/code/Wyomind/Core/Observer/ControllerActionPredispatch.php
rmdir  ./app/code/Wyomind/DataFeedManager/view/adminhtml/web/images
rmdir  ./app/code/Wyomind/DataFeedManager/Model/ResourceModel/Store
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/xml
rmdir  ./app/code/Wyomind/DataFeedManager/Block/Adminhtml/Variables
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/css
rm ./app/code/Wyomind/DataFeedManager/Block/Adminhtml/Variables.php
rm ./app/code/Wyomind/DataFeedManager/Helper/AttributesReviews.php
rm ./app/code/Wyomind/DataFeedManager/Helper/AttributesDefault.php
rmdir  ./app/code/Wyomind/DataFeedManager/data/Google/Requirements
rm ./app/code/Wyomind/DataFeedManager/Console/Command/Generate.php
rmdir  ./app/code/Wyomind/DataFeedManager/view/adminhtml/templates
rm ./app/code/Wyomind/DataFeedManager/Model/Product/Collection.php
rm ./app/code/Wyomind/DataFeedManager/Helper/AttributesImages.php
rmdir  ./app/code/Wyomind/Core/Block/Adminhtml/System/Config/Form
rm ./app/code/Wyomind/DataFeedManager/Console/Command/Listing.php
rm ./app/code/Wyomind/DataFeedManager/Model/Config/UrlRewrite.php
rm ./app/code/Wyomind/DataFeedManager/Helper/AttributesPrices.php
rm ./app/code/Wyomind/DataFeedManager/Helper/DataFeedManager.php
rmdir  ./app/code/Wyomind/DataFeedManager/view/adminhtml/web/css
rmdir  ./app/code/Wyomind/DataFeedManager/data/Google/Taxonomies
rm ./app/code/Wyomind/DataFeedManager/Block/Adminhtml/Feeds.php
rmdir  ./app/code/Wyomind/DataFeedManager/view/adminhtml/layout
rmdir  ./app/code/Wyomind/DataFeedManager/Block/Adminhtml/Feeds
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror
rm ./app/code/Wyomind/Core/Controller/Activation/Webservice.php
rmdir  ./app/code/Wyomind/DataFeedManager/view/adminhtml/web/js
rmdir  ./app/code/Wyomind/DataFeedManager/view/adminhtml/email
rm ./app/code/Wyomind/DataFeedManager/Helper/AttributesUrl.php
rm ./app/code/Wyomind/DataFeedManager/etc/adminhtml/routes.xml
rmdir  ./app/code/Wyomind/DataFeedManager/Controller/Adminhtml
rm ./app/code/Wyomind/DataFeedManager/etc/adminhtml/system.xml
rm ./app/code/Wyomind/DataFeedManager/etc/email_templates.xml
rmdir  ./app/code/Wyomind/DataFeedManager/Model/ResourceModel
rm ./app/code/Wyomind/DataFeedManager/Helper/CategoryTree.php
rm ./app/code/Wyomind/DataFeedManager/etc/frontend/routes.xml
rm ./app/code/Wyomind/DataFeedManager/Setup/UpgradeSchema.php
rm ./app/code/Wyomind/DataFeedManager/Setup/InstallSchema.php
rmdir  ./app/code/Wyomind/Core/Block/Adminhtml/System/Config
rm ./app/code/Wyomind/DataFeedManager/etc/adminhtml/menu.xml
rm ./app/code/Wyomind/Core/view/adminhtml/web/css/system.css
rmdir  ./app/code/Wyomind/DataFeedManager/view/adminhtml/web
rm ./app/code/Wyomind/DataFeedManager/Logger/HandlerCron.php
rm ./app/code/Wyomind/DataFeedManager/Logger/LoggerCron.php
rm ./app/code/Wyomind/DataFeedManager/Setup/UpgradeData.php
rm ./app/code/Wyomind/DataFeedManager/Setup/InstallData.php
rm ./app/code/Wyomind/DataFeedManager/Helper/Attributes.php
rm ./app/code/Wyomind/Core/Model/ResourceModel/Schedule.php
rm ./app/code/Wyomind/DataFeedManager/Controller/Feeds.php
rmdir  ./app/code/Wyomind/DataFeedManager/Controller/Feeds
rm ./app/code/Wyomind/Core/Plugin/Config/Model/Config.php
rm ./app/code/Wyomind/Core/Model/ResourceModel/Config.php
rm ./app/code/Wyomind/DataFeedManager/Model/Functions.php
rm ./app/code/Wyomind/DataFeedManager/Model/Variables.php
rmdir  ./app/code/Wyomind/DataFeedManager/Block/Adminhtml
rmdir  ./app/code/Wyomind/DataFeedManager/Console/Command
rm ./app/code/Wyomind/DataFeedManager/Model/Observer.php
rmdir  ./app/code/Wyomind/DataFeedManager/view/adminhtml
rm ./app/code/Wyomind/DataFeedManager/Logger/Handler.php
rm ./app/code/Wyomind/DataFeedManager/Helper/Storage.php
rm ./app/code/Wyomind/DataFeedManager/Helper/Parser.php
rmdir  ./app/code/Wyomind/DataFeedManager/Model/Product
rm ./app/code/Wyomind/DataFeedManager/Logger/Logger.php
rmdir  ./app/code/Wyomind/DataFeedManager/etc/adminhtml
rmdir  ./app/code/Wyomind/DataFeedManager/Model/Config
rmdir  ./app/code/Wyomind/Core/view/frontend/templates
rmdir  ./app/code/Wyomind/DataFeedManager/etc/frontend
rm ./app/code/Wyomind/DataFeedManager/registration.php
rmdir  ./app/code/Wyomind/DataFeedManager/data/Google
rm ./app/code/Wyomind/DataFeedManager/Helper/Data.php
rmdir  ./app/code/Wyomind/Core/Block/Adminhtml/System
rm ./app/code/Wyomind/DataFeedManager/etc/crontab.xml
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/css
rm ./app/code/Wyomind/DataFeedManager/Model/Feeds.php
rmdir  ./app/code/Wyomind/Core/Controller/Activation
rmdir  ./app/code/Wyomind/Core/view/adminhtml/layout
rm ./app/code/Wyomind/DataFeedManager/i18n/en_US.csv
rm ./app/code/Wyomind/DataFeedManager/i18n/fr_FR.csv
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js
rmdir  ./app/code/Wyomind/DataFeedManager/Controller
rm ./app/code/Wyomind/DataFeedManager/etc/config.xml
rm ./app/code/Wyomind/DataFeedManager/etc/module.xml
rmdir  ./app/code/Wyomind/Core/view/frontend/layout
rm ./app/code/Wyomind/Core/etc/adminhtml/events.xml
rm ./app/code/Wyomind/Core/etc/adminhtml/system.xml
rm ./app/code/Wyomind/DataFeedManager/composer.json
rmdir  ./app/code/Wyomind/Core/Plugin/Config/Model
rm ./app/code/Wyomind/Core/Model/Notifications.php
rmdir  ./app/code/Wyomind/Core/Model/ResourceModel
rm ./app/code/Wyomind/Core/etc/frontend/routes.xml
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web
rmdir  ./app/code/Wyomind/DataFeedManager/Console
rm ./app/code/Wyomind/DataFeedManager/LICENSE.TXT
rm ./app/code/Wyomind/DataFeedManager/etc/acl.xml
rmdir  ./app/code/Wyomind/DataFeedManager/Helper
rm ./app/code/Wyomind/DataFeedManager/etc/di.xml
rmdir  ./app/code/Wyomind/DataFeedManager/Logger
rmdir  ./app/code/Wyomind/DataFeedManager/Model
rmdir  ./app/code/Wyomind/DataFeedManager/Setup
rm ./app/code/Wyomind/Core/Block/Webservice.php
rm ./app/code/Wyomind/Core/etc/adminhtml/di.xml
rmdir  ./app/code/Wyomind/DataFeedManager/Block
rmdir  ./app/code/Wyomind/DataFeedManager/data
rmdir  ./app/code/Wyomind/DataFeedManager/view
rmdir  ./app/code/Wyomind/Core/Block/Adminhtml
rmdir  ./app/code/Wyomind/DataFeedManager/i18n
rmdir  ./app/code/Wyomind/DataFeedManager/etc
rmdir  ./app/code/Wyomind/Core/view/adminhtml
rm ./app/code/Wyomind/Core/Logger/Handler.php
rmdir  ./app/code/Wyomind/Core/view/frontend
rmdir  ./app/code/Wyomind/Core/Plugin/Config
rmdir  ./app/code/Wyomind/Core/etc/adminhtml
rm ./app/code/Wyomind/Core/Logger/Logger.php
rmdir  ./app/code/Wyomind/Core/etc/frontend
rm ./app/code/Wyomind/Core/registration.php
rm ./app/code/Wyomind/Core/Helper/Data.php
rm ./app/code/Wyomind/Core/Helper/Core.php
rm ./app/code/Wyomind/Core/etc/config.xml
rm ./app/code/Wyomind/Core/Model/Feed.php
rm ./app/code/Wyomind/Core/etc/module.xml
rmdir  ./app/code/Wyomind/Core/Controller
rmdir  ./app/code/Wyomind/DataFeedManager
rm ./app/code/Wyomind/Core/composer.json
rmdir  ./app/code/Wyomind/Core/Observer
rm ./app/code/Wyomind/Core/LICENSE.TXT
rm ./app/code/Wyomind/Core/etc/di.xml
rmdir  ./app/code/Wyomind/Core/Logger
rmdir  ./app/code/Wyomind/Core/Helper
rmdir  ./app/code/Wyomind/Core/Plugin
rmdir  ./app/code/Wyomind/Core/Model
rmdir  ./app/code/Wyomind/Core/Block
rmdir  ./app/code/Wyomind/Core/view
rmdir  ./app/code/Wyomind/Core/etc
rmdir  ./app/code/Wyomind/Core
rmdir  ./app/code/Wyomind
rmdir  ./app/code
rmdir  ./app