<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Preorder
 */
?>
<?php /* @var $block \Amasty\Preorder\Block\Product\View\Preorder\ProductBundle */?>
<?php
if(!$block->canShowBlock()) {
    return;
}
?>
<script type="text/javascript">
    require(['jquery', 'Amasty_Preorder/js/product/preorder_bundle'], function($) {
        $widget = $.mage.amastyPreorderBundle({
            isAllProductsPreorder: <?=(int)$block->getIsAllProductsPreorder();?>,
            preOrderNote: '<?=$block->getPreorderNote();?>',
            addToCartLabel: '<?=$block->getCartLabel();?>',
            map: <?=json_encode($block->getMap());?>,
            optionsData: <?=json_encode($block->getBundleOptionsData());?>
        });
    });
</script>
