<div class="blackbox draggable">
    <div class="resizable">
        <div class="header">
            <span class="button preview">Preview</span>
            <span class="button library active">Library</span>
            <span class="button close"></span>
            <span class="button fullscreen"></span>
        </div>
        <div class="content">
            <div class="area preview xml"><textarea id="cm-preview"></textarea></div>
            <div class="area preview csv"></div>
            <div class="area library"></div>
            <div class="area error message message-error error"><div class="msg">Error</div></div>
            <div class="area loader"></div>
        </div>
    </div>
</div>

<script>
    require(["jquery","jquery/ui","dfm_blackbox"], function ($, ui, blackbox) {
        'use strict';
            $(".blackbox.draggable").draggable({
                handle: ".header",
                stop: function (et, ui) {
                    blackbox.savePosition(ui.position);
                }
            });
            $(".blackbox .resizable").resizable({
                stop: function (evt, ui) {
                    blackbox.saveSize(ui.size);
                }
            });

            blackbox.setPositionAndSize();

            blackbox.previewArea = CodeMirror.fromTextArea(document.getElementById('cm-preview'), {
                matchBrackets: true,
                mode: "application/x-httpd-php",
                indentUnit: 2,
                indentWithTabs: false,
                lineWrapping: true,
                lineNumbers: true,
                styleActiveLine: true
            });

            $(".blackbox .button.preview").on('click', function () {
                blackbox.refreshPreview();
            });
            $(".blackbox .button.library").on('click', function () {
                blackbox.refreshLibrary();
            });
            /* click on an attribute load sample */
            $(document).on('click', '.load-attr-sample', function () {
                blackbox.loadLibrarySamples($(this));
            });
            
            blackbox.refreshLibrary();
    });
</script>