<script>
    
    /* for code mirror syntactic coloration */
    var DataFeedManager = {};
    
    var Utils = {
        sampleUrl : '<?php echo $block->getUrl("*/*/sample"); ?>',
        libraryUrl : '<?php echo $block->getUrl("*/*/library"); ?>',
        librarySampleUrl : '<?php echo $block->getUrl("*/*/librarysample"); ?>',
        categoriesUrl : '<?php echo $block->getUrl("*/*/categories"); ?>'
    }
</script>