<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile


?>
<div class="footer-container">
    <div class="footer content">
        <div class="row footer-inner">
            <div class="col-md-2 col-sm-3 col-xs-12  ">
                <div class="footer-heading"><?php echo __('Popular Searches')?></div>
                <ul class="footer links">
                    <li clas="nav item">
                        <a href="/living-room-ff/sofas-ff/leather-sofas.html"><?php echo __('Leather Sofas')?></a>
                    </li>
                    <li clas="nav item">
                        <a href="/bedroom-ff/beds-ff/leather-bed-frames-ff.html"><?php echo __('Leather Beds & Frames')?></a>
                    </li>
                    <li clas="nav item">
                        <a href="/dining-room-ff/dining-sets-119-ff/marble-dining-sets.html"><?php echo __('Marble Dining Sets')?></a>
                    </li>
                    <li clas="nav item">
                        <a href="/dining-room-ff/dining-sets-119-ff/high-gloss-dining-sets.html"><?php echo __('High Gloss Dining Sets')?></a>
                    </li>
                    <li clas="nav item">
                        <a href="/garden-ff/rattan-garden-sets.html"><?php echo __('Rattan Garden Furniture')?></a>
                    </li>
                    <li clas="nav item">
                        <a href="/conservatory-ff/conservatory-sets-ff.html"><?php echo __('Conservatory Sets')?></a>
                    </li>
                    <li clas="nav item">
                        <a href="/lighting-ff/table-lamps-ff.html"><?php echo __('Table Lamps By RV Astley')?></a>
                    </li>
                </ul>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12 ">
                <div class="footer-heading"><?php echo __('Customer Service')?></div>
                <ul class="footer links">
                    <li clas="nav item">
                        <a href="/delivery-information/"><?php echo __('Delivery Information')?></a>
                    </li>
                    <li clas="nav item">
                        <a href="/contact/"><?php echo __('Contact Us')?></a>
                    </li>
                    <li clas="nav item">
                        <a href="/returns-policy/"><?php echo __('Returns Policy')?></a>
                    </li>
                    <li clas="nav item">
                        <a href="/faq/"><?php echo __('FAQ')?></a>
                    </li>
                </ul>
               
                <div class="footer-heading"><?php echo __('About Us')?></div>
                <ul class="footer links">
                    <li clas="nav item">
                        <a href="/the-company/"><?php echo __('The Company')?></a>
                    </li>
                    <li clas="nav item">
                        <a href="/terms-and-conditions/"><?php echo __('Terms & Conditions')?></a>
                    </li>
                    <li clas="nav item">
                        <a href="/security/"><?php echo __('Security')?></a>
                    </li>
                    <li clas="nav item">
                        <a href="/privacy-policy-cookie-restriction-mode/"><?php echo __('Privacy')?></a>
                    </li>
                    <li clas="nav item">
                        <a href=""><?php echo __('Our Blog')?></a>
                    </li>
                    <li clas="nav item">
                        <a href=""><?php echo __('Sitemap')?></a>
                    </li>
                </ul>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12 ">
                <div class="footer-heading"><?php echo __('Here to help')?></div>
                <ul class="footer links">
                    <li clas="nav item">
                        <a href="/discount-codes/"><?php echo __('Discount Codes')?></a>
                    </li>
                    <li clas="nav item">
                        <a href="/price-promise/"><?php echo __('Price Promise')?></a>
                    </li>
                </ul>
                
                <div class="footer-heading"><?php echo __('My Account')?></div>
                <ul class="footer links">
                    <li clas="nav item">
                        <a href="/customer/account/login/"><?php echo __('Register')?></a>
                    </li>
      
                </ul>
            </div>
            <div class="col-md-4 col-sm-3 col-xs-12 ">
                <div class="footer-heading"><?php echo __('Follow Us')?></div>
                <ul class="footer social">
                    <li clas="nav item">
                        <a href="https://www.facebook.com/1stfurniture/"> <img src="https://www.firstfurniture.co.uk/pub/static/version1518763821/frontend/Morale/Firstfurniture/web/images/facebook.gif" alt="firstfurniture.co.uk on facebook" width="24" height="24"> </a>
                    </li>
                    <li clas="nav item">
                        <a href="#"> <img src="https://www.firstfurniture.co.uk/pub/static/version1518763821/frontend/Morale/Firstfurniture/web/images/twitter.gif" alt="first furniture on twitter" width="24" height="24"> </a>
                    </li>
                </ul>
               
                <div class="footer-heading"><?php echo __('Top Brands')?></div>
                <div class="footer links">               
                    <a href="/brands-ff/bentley-designs-ff.html"><?php echo __('Bentley Designs')?></a>
                    <a href="/brands-ff/alstons-ff.html"><?php echo __('Alstons Sofas')?></a>
                    <a href="/brands-ff/sealy-ff.html"><?php echo __('Sealy Mattress')?></a>
                    <a href="/brands-ff/limelight-ff.html"><?php echo __('LimeLight Beds')?></a>
                    <a href="/brands-ff/chelsom-furniture-ff.html"><?php echo __('Chelsom Furniture')?></a>
                    <a href="/brands-ff/hartman-garden-furniture-ff.html"><?php echo __('Hartman Furniture')?></a>
                    <a href="/brands-ff/royalcraft-furniture-ff.html"><?php echo __('RoyalCraft Furniture')?></a>
                    <a href="/brands-ff/fairmont-furniture-ff.html"><?php echo __('Fairmont Furniture')?></a>
                </div>
				<div class="footer-heading"><?php echo __('Top Category')?></div>
                <div class="footer links">               
                    <a href="/dining-room-ff.html"><?php echo __('Dining Room')?></a>
                    <a href="/bedroom-ff.html"><?php echo __('Bedroom Furniture')?></a>
                    <a href="/living-room-ff.html"><?php echo __('Living Room')?></a>
                    <a href="/garden-ff.html"><?php echo __('Garden Furniture')?></a>
                   <a href="/conservatory-ff.html"><?php echo __('Conservatory Furniture')?></a>
                </div>
            </div>
            </div>
			
        </div>
        <div class="row footer-inner">
            <div class="col-md-12 text-center"><img src="https://www.firstfurniture.co.uk/pub/static/version1518763821/frontend/Morale/Firstfurniture/web/images/cards.png" alt="secure payment on Firstfurniture.co.uk" /></div>
        </div>
    </div>
</div>
<!-- begin olark code -->
<script type="text/javascript" async>
  ;(function(o,l,a,r,k,y){if(o.olark)return;
  r="script";y=l.createElement(r);r=l.getElementsByTagName(r)[0];
  y.async=1;y.src="//"+a;r.parentNode.insertBefore(y,r);
  y=o.olark=function(){k.s.push(arguments);k.t.push(+new Date)};
  y.extend=function(i,j){y("extend",i,j)};
  y.identify=function(i){y("identify",k.i=i)};
  y.configure=function(i,j){y("configure",i,j);k.c[i]=j};
  k=y._={s:[],t:[+new Date],c:{},l:a};
  })(window,document,"static.olark.com/jsclient/loader.js");
  /* Add configuration calls below this comment */
  olark.identify("8376-647-10-9815");
</script>
<!-- end olark code -->

