<?php
/**
* Copyright 2016 aheadWorks. All rights reserved.
* See LICENSE.txt for license details.
*/

// @codingStandardsIgnoreFile

/* @var \Aheadworks\Autorelated\Block\Adminhtml\Rule\Listing\Column\Renderer\Header\ProductConditionType $block */
?>

<div class="col-header"><?php /* @noEscape */ echo $block->getHeaderName(); ?></div>
<div class="admin__field-tooltip">
    <span class="admin__field-tooltip-action action-help"></span>
    <div class="admin__field-tooltip-content"><?php /* @noEscape */ echo $block->getHeaderTooltipText(); ?></div>
</div>
