<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Preorder
 */
?>
<?php
/**
 * @var $block \Amasty\Preorder\Block\Product\View\Preorder\ProductConfigurable
 */
?>
<script type="text/javascript">
    require(['jquery', 'Amasty_Preorder/js/product/preorder_configurable_list'], function($) {
       $widget = $.mage.amastyPreorderConfigurable({
            entity: <?= $block->getProductId()?>,
            swatchOpt: $(".swatch-opt-<?= $block->getEntityId()?>"),
            addToCartButton: $(".swatch-opt-<?= $block->getEntityId()?>").nextAll('.product-item-inner').find('button'),
            addToCartLabel: '<?=$block->getCartLabel();?>',
            map: <?=$block->getJsonProductPreorderMap();?>,
            currentAttributes: <?=$block->getJsonCurrentAttributeArray();?>
        });
    });
</script>
