<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>
<?php $_helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
<?php $_product = $block->getProduct(); ?>
<div class="product-add-form">
    <?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $productStockObj = $objectManager->get('Magento\CatalogInventory\Api\StockRegistryInterface')->getStockItem($_product->getId());
    ?>
    <form action="<?php /* @escapeNotVerified */ echo $block->getSubmitUrl($_product) ?>" method="post"
          id="product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $_product->getId() ?>" />
        <input type="hidden" name="selected_configurable_option" value="" />
        <input type="hidden" name="related_product" id="related-products-field" value="" />
        <?php echo $block->getBlockHtml('formkey')?>
        <?php echo $block->getChildHtml('form_top'); ?>
        <?php if (!$block->hasOptions()):?>
            <?php echo $block->getChildHtml('product_info_form_content'); ?>
        <?php else:?>
            <?php if ($_product->isSaleable() && $block->getOptionsContainer() == 'container1'):?>
                <?php echo $block->getChildChildHtml('options_container') ?>
            <?php endif;?>
        <?php endif; ?>

        <?php if ($_product->isSaleable() && $block->hasOptions() && $block->getOptionsContainer() == 'container2'):?>
            <?php echo $block->getChildChildHtml('options_container') ?>
        <?php endif;?>
        <?php echo $block->getChildHtml('form_bottom'); ?>
    </form>
</div>
<h4 style="text-align:center;"><?php echo('Need Assistance? Call: <a href="tel:0800 975 0508"><span style="color:#000;font-weight:bold;">0800 975 0508</span></a>');?></h4>
<?php if($_product->getBlackfri() != ''):?>
<?php 
$attr = $_product->getResource()->getAttribute('blackfri');
 if ($attr->usesSource()) {
    $optionText = $attr->getSource()->getOptionText($_product->getBlackfri());
 }
 ?>

<div class="row mt10 pb10 bbc promo-product-img">
    <div class="col-md-12">
       <img src='<?php echo $this->getViewFileUrl('images/productpageimages/'.strtolower($optionText).'.png'); ?>' alt="<?php echo $optionText?>" class="img-responsive">
    </div>
</div>
<?php endif;?>
<div class="row inst-btn">
    <?php  $attr = $_product->getResource()->getAttribute('leadtime');?>
    <?php //echo $attr->getSource()->getOptionText($_product->getLeadtime())?>
    <?php if($attr->usesSource()):?>
    <div class="col-md-6 col-sm-12">
        <a class="btn btn-default product-btn" href="javascript: void(0)">
            <i class="fa fa-clock-o"></i>
            <span class="btn-right-container">
                <span class="label"><?php echo __('Delivery Time')?></span>
                <span class="clr-pink">
                    <?php echo $attr->getSource()->getOptionText($_product->getLeadtime());?>
                </span>
            </span>
        </a>
    </div>
    <?php endif;?>
    <div class="col-md-6 col-sm-12">
        <a class="btn btn-default product-btn" href="javascript: void(0)" data-toggle="modal" data-target="#freedeliveryModal">
            <i class="fa fa-truck"></i>
            <span class="btn-right-container">
                <span class="label"><?php echo __('Free Delivery')?></span>
                <span class="clr-pink fa-12"><?php echo __('To Mainland UK*')?></span>
            </span>
        </a>
    </div>
</div>
<div class="discount_chooseus">
    <div class="col-md-6 col-sm-12">
        <a class="btn btn-default product-btn" href="javascript: void(0)" data-toggle="modal" data-target="#volumeModal">
            <i class="fa fa-tag clr-pink"></i>
            <span class="btn-right-container">
                <span class="label clr-black"><?php echo __('Volume Discount')?></span>
            </span>
        </a>
    </div>
    <div class="col-md-6 col-sm-12">
        <a class="btn btn-default product-btn" href="javascript: void(0)" data-toggle="modal" data-target="#whychooseModal">
            <i class="fa fa-rocket clr-pink"></i>
            <span class="btn-right-container">
                <span class="label clr-black"><?php echo __('Why Choose Us?')?></span>
            </span>
        </a>
    </div>
</div>
<table style="border-bottom: 1px solid #ddd;margin-bottom: 10px;padding: 0px 0px 15px 0px;">
				<tr>
					<td>
						<a id="price_promise1" class="swing animated infinite" href="javascript: void(0)" data-toggle="modal" data-target="#pricepromiseModal">
							<img src='<?php echo $this->getViewFileUrl('images/price-promise.jpg');?>' alt="price promise" class="pricepromiseimg"/> 
						</a>
					</td>
					<td class="pricepromisedesc">
						<p>
						In the unlikely event of finding this product cheaper elsewhere, we will beat our competitors price. Call us on <span style="color:#DE0D8B;">0800 975 0508</span> to discuss.
						</p>
					</td>
				</tr>
			</table>
<table style="border-border: 1px solid #ddd; margin-bottom: 10px; padding: 0px 0px 15px 0px;">
    <tr>
        <td style="background-color:#f5f5f5; color:#de0e8a; text-align: center; border: 1px solid #c1c1c1;">
            <?php echo $this->getChildHtml('productcategoryinfo');?>
        </td>
    </tr>
</table>
<script>
    require([
        'jquery',
        'priceBox',
        'Magento_Catalog/js/price-utils'
    ], function($){
        var dataPriceBoxSelector = '[data-role=priceBox]',
            dataProductIdSelector = '[data-product-id=<?php echo $block->escapeHtml($_product->getId())?>]',
            priceBoxes = $(dataPriceBoxSelector + dataProductIdSelector);

        priceBoxes = priceBoxes.filter(function(index, elem){
            return !$(elem).find('.price-from').length;
        });

        priceBoxes.priceBox({'priceConfig': <?php /* @escapeNotVerified */ echo $block->getJsonConfig() ?>});
        $('.page-title-wrapper .page-title').click(function(){
            $('#AOPriceMatch').toggleClass('hide');
        });
        $(document).mouseup(function(e) 
        {
            var container = $(".page-title-wrapper");
        
            // if the target of the click isn't the container nor a descendant of the container
            if (!container.is(e.target) && container.has(e.target).length === 0) 
            {
                $('#AOPriceMatch').addClass('hide');
            }
        });
        //$(document).on("change", ".product-custom-option", function(){ alert("d");
        $(".product-custom-option").change(function(){ 
            var currencySymbol = $("#final-price-span").attr('data-currency');
            var productPriceCustom = parseInt($("#final-price-span").attr('data-actual-price'));
            $(".product-custom-option").each(function() {
                var customoptionPrice = parseInt($(this).find(':selected').attr('price'));
                if(isNaN(customoptionPrice)) {
                    
                }
                else
                {
                    var formatedPrice = customoptionPrice+productPriceCustom;
                    //$("#final-price-span").html(customoptionPrice+productPriceCustom);
                    $("#final-price-span").attr('data-price', formatedPrice);
                    var displayPrice = parseFloat($("#final-price-span").attr('data-price'), 10).toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, "$1,").toString()
                    $("#final-price-span").text(currencySymbol+ displayPrice);
                }
                
            });
        });
        $(document).on("change", ".super-attribute-select", function(){
            var optionSelected ='';
            var i=0;
            var totalOption=0;
            $(".super-attribute-select").each(function() {
                if(i==0)
                {
                    optionSelected = $(this).val();
                    totalOption++;
                }
                else if($(this).val() != '')
                {
                    optionSelected = optionSelected+","+$(this).val();
                    totalOption++;
                }
                i++;
            });
            if(optionSelected != '' && i == totalOption)
            {
                //alert();
                $.ajax({
                    url: '<?php echo $block->getBaseUrl() ?>getoptionprice.php',
                    type: 'POST',
                    data: { productId : '<?php echo $_product->getId()?>', option_selected : optionSelected},
                    success: function(data) {
                        $('#final-price-span').html(data)
                    }
               });
            }
            else
            {
                var productprice = parseFloat($('#final-price-span').attr('data-actual-price'));
                $('#final-price-span').html($('#final-price-span').attr('data-currency')+productprice.toFixed(2));
            }
        });
        var secondLastChile = $( ".breadcrumbs ul li:nth-last-child(2)" ).find('a');
        $("a#view-prev-cat").attr('href', secondLastChile.attr('href'));
        $("a#view-prev-cat").html($( "a#view-prev-cat" ).html()+secondLastChile.html());
    });
</script>
<div id="pricepromiseModal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">

    <!-- Modal content-->
    <div class="modal-content">
        <!--<div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title"><?php //echo __('Why Choose Us?')?></h4>
        </div>-->
        <div class="modal-body">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('price_promise')->toHtml();?>
        </div>
    </div>

  </div>
</div>
<div id="whychooseModal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">

    <!-- Modal content-->
    <div class="modal-content">
        <!--<div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title"><?php //echo __('Why Choose Us?')?></h4>
        </div>-->
        <div class="modal-body">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('why_choose_us')->toHtml();?>
        </div>
    </div>

  </div>
</div>
<div id="volumeModal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">

    <!-- Modal content-->
    <div class="modal-content">
      <!--<div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><?php //echo __('Volume Discount')?></h4>
      </div>-->
      <div class="modal-body">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('volume_discount')->toHtml();?>
      </div>
    </div>

  </div>
</div>
<div id="freedeliveryModal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">

    <!-- Modal content-->
    <div class="modal-content">
      <!--<div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><?php //echo __('Volume Discount')?></h4>
      </div>-->
      <div class="modal-body">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('free_delivery')->toHtml();?>
      </div>
    </div>

  </div>
</div>

<div id="cartSuccessModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-body">
        <div class="alert alert-success"><?php echo __('')?></div>
        <div class="cart-success-container">
            <div class="cart-p-image pull-left">Image</div>
            <div class="pull-right">
                <p>Product Name</p>
                <p>Code</p>
                <div class="action-btn">
                    <a href="javascript: void(0)"><?php echo __('Contiue Shopping')?></a>
                    <a href="javascript: void(0)"><?php echo __('View Basker and Checkout')?></a>
                </div>
            </div>
        </div>
      </div>
    </div>

  </div>
</div>
